name: fwfh_just_audio
version: 0.14.3
description: WidgetFactory extension to render AUDIO with the just_audio plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.10.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.8.0 <0.16.0"
  just_audio: ">=0.9.0 <0.10.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  just_audio_platform_interface: ">=4.0.0 <5.0.0"
  lint: any
  tuple: any

flutter:
  uses-material-design: true

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - fwfh
