name: flutter_widget_from_html
version: 0.4.1-rc.2020052701
description: Flutter plugin for widget tree building from html that supports hyperlink, image, nested list, etc.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=1.10.15-pre.148 <2.0.0"
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  flutter_widget_from_html_core: ^0.4.1-rc.2020052701
  html: ^0.14.0+3
  url_launcher: ^5.4.2
  video_player: ^0.10.8+1
  webview_flutter: ^0.3.19+9

dependency_overrides:
  flutter_widget_from_html_core:
    path: packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
