name: flutter_widget_from_html
version: 0.2.3+2
description: Flutter plugin for widget tree building from html that supports hyperlink, image, nested list, etc.
author: Dao Hoang Son <daohoangson@gmail.com>
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^1.1.1
  chewie: ^0.9.8
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    path: packages/core
  html: ^0.14.0+2
  url_launcher: ^5.1.3
  video_player: ^0.10.2+1
  webview_flutter: ^0.3.14+1

dev_dependencies:
  flutter_test:
    sdk: flutter
