name: flutter_widget_from_html
version: 0.0.2
description: Flutter plugin for widget tree building from html.
author: Dao Hoang Son <daohoangson@gmail.com>
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^0.4.2
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    path: ./packages/core
  url_launcher: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  html: ^0.13.3
