name: flutter_widget_from_html
version: 0.3.2-rc
description: Flutter plugin for widget tree building from html that supports hyperlink, image, nested list, etc.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=1.6.7 <1.10.15"
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  cached_network_image: ^2.0.0-rc.1
  chewie: ^0.9.8+1
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: 0.2.4+3
  html: ^0.14.0+3
  url_launcher: ^5.2.5
  video_player: ^0.10.2+5
  webview_flutter: ^0.3.15+1

dev_dependencies:
  flutter_test:
    sdk: flutter
