name: fwfh_text_style
version: 2.7.0-beta.1
description: A TextStyle replacement that allows resetting height behavior to normal.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.7.0-3.0.pre"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
