name: fwfh_cached_network_image
version: 0.14.3
description: WidgetFactory extension to render IMG with cached_network_image plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.10.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cached_network_image: ^3.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0
  flutter_widget_from_html_core: "<0.16.1"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  lint: any
  mocktail: ^1.0.0

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - img
  - fwfh
