name: fwfh_cached_network_image
version: 0.6.1+2
description: WidgetFactory extension to render IMG with cached_network_image plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.0.0
  flutter_widget_from_html_core: ">=0.6.0 <0.8.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  file: any
  flutter_test:
    sdk: flutter
  mocktail: any
  pedantic: any
