name: fwfh_svg
version: 0.7.0+1
description: WidgetFactory extension to render SVG with flutter_svg plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.2.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=0.21.0 <0.23.0"
  flutter_widget_from_html_core: ">=0.7.0 <0.9.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  mocktail: any

flutter:
  assets:
    - test/images/
