name: fwfh_svg
version: 0.7.2
description: WidgetFactory extension to render SVG with flutter_svg plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.5.0"
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ">=0.23.0+1 <2.0.0"
  flutter_widget_from_html_core: ">=0.7.0 <0.9.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.12.0
  lint: any
  mocktail: ^0.2.0

flutter:
  assets:
    - test/images/
