name: flutter_widget_from_html_core
version: 0.2.0
description: Flutter plugin for widget tree building from html that focuses on correctness and extensibility.
author: Dao Hoang Son <daohoangson@gmail.com>
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
