name: flutter_widget_from_html_core
version: 0.6.0
description: Flutter package for widget tree building from html that focuses on correctness and extensibility.
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  csslib: ^0.17.0
  flutter:
    sdk: flutter
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.9.0
  mocktail_image_network: ^0.1.0
  pedantic: ^1.10.0
  test: any

flutter:
  assets:
    - test/images/
