name: flutter_widget_from_html_core
version: 0.5.2+1
description: Flutter package for widget tree building from html that focuses on correctness and extensibility.
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  # Stack.clipBehavior https://github.com/flutter/flutter/commit/42e02d60d3104e97161ba597103854557b2d72ee
  flutter: ">=1.20.0 <2.0.0"
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.6.0
  network_image_mock: ^1.0.1
  pedantic: ^1.9.0
  test: any

flutter:
  assets:
    - test/images/
