name: flutter_widget_from_html_core
version: 0.5.0
description: Flutter package for widget tree building from html that focuses on correctness and extensibility.
homepage: https://github.com/daohoangson/flutter_widget_from_html/tree/master/packages/core

environment:
  flutter: ">=1.6.7 <2.0.0"
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^1.0.1
  pedantic: ^1.9.0
  test: any
