name: fwfh_chewie
version: 0.16.0
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.10.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  chewie: ^1.3.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.14.2 <0.17.0"
  video_player: ^2.2.9

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  plugin_platform_interface: any
  video_player_platform_interface: 6.2.0

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - video
  - fwfh
