name: fwfh_chewie
version: 0.12.0-alpha.1
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  chewie: ^1.0.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.13.0-0
  video_player: ^2.2.9

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  plugin_platform_interface: any
  video_player_platform_interface: ">=5.0.0 <7.0.0"
