name: fwfh_chewie
version: 0.6.2
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  chewie: ^1.0.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.6.0 <0.8.0"
  video_player: ^2.0.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  video_player_platform_interface: any
