name: Android Test
on:
  push:
    paths:
      - .github/workflows/android.yml
      - "packages/fwfh_chewie/lib/src/video_player/**"
      - "packages/fwfh_webview/lib/src/web_view/**"
      - "tool/sylph/**"

jobs:
  sylph:
    environment:
      name: aws
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Run sylph.sh
        env:
          AWS_ACCESS_KEY_ID: AKIAY43IFJQXAVHHHXQ6
          AWS_DEFAULT_REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set -e

          sudo snap install yq

          exec ./tool/sylph/sylph.sh
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          path: /tmp/sylph_artifacts
