name: Android Test
on:
  push:
    paths: 
      - .github/workflows/android.yml
      - packages/enhanced/lib/src/widgets/video_player.dart
      - packages/enhanced/lib/src/widgets/web_view.dart
      - 'packages/enhanced/lib/src/widgets/web_view/**'
      - 'tool/sylph/**'

jobs:
  sylph:
    if: ${{ github.repository_owner == 'daohoangson' }}
    environment:
      name: aws
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: beta
      - name: Run sylph.sh
        env:
          AWS_ACCESS_KEY_ID: AKIAY43IFJQXLQIQNSY4
          AWS_DEFAULT_REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          set -e

          brew install yq

          exec ./tool/sylph/sylph.sh
