name: Backward compatibility
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        package:
          - core
          - enhanced
          - fwfh_cached_network_image
          - fwfh_chewie
          - fwfh_svg
          - fwfh_text_style
          - fwfh_url_launcher
          - fwfh_webview

    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - uses: actions/checkout@v2
      - name: Update pubspec.yaml
        run: |
          set -e

          sudo snap install yq

          # delete all overrides and use pub.dev versions
          yq e 'del(.dependency_overrides)' -i pubspec.yaml

          # back up SDK constraint
          _sdkVersion=$( yq e .environment.sdk pubspec.yaml )

          # replace:
          #   foo: ^1.0.0
          #   bar: ^2.0.0-0
          # into:
          #   foo: 1.0.0
          #   bar: ^2.0.0-0 (unchanged)
          sed -i'' -e 's#^\(  [^:]*\): ^\([0-9.]*\)$#\1: \2#' pubspec.yaml

          # replace:
          #   foo: ">=1.0.0" 
          #   bar: ">=2.0.0 <4.0.0"
          # into:
          #   foo: 1.0.0
          #   bar: 2.0.0
          sed -i'' -e 's#^\(  [^:]*\): ">=\([0-9.]*\)\( <.*\)\{0,1\}"$#\1: \2#' pubspec.yaml

          # restore SDK constraint
          yq e ".environment.sdk = \"${_sdkVersion}\"" -i pubspec.yaml

          # extract Flutter version to install later
          _flutterVersion=$( yq e '.environment.flutter' pubspec.yaml )
          echo "FLUTTER_VERSION=${_flutterVersion}" >> $GITHUB_ENV

          # output for debugging
          cat pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - run: flutter test

  fwfh_text_style:
    strategy:
      matrix:
        channel:
          - beta
          - master

    # In case one of these fails, create a new PR against the `release/*` branch
    # and publish a new version to make sure there is a compatible version
    # of `fwfh_text_style` for all active Flutter versions.
    name: fwfh_text_style@${{ matrix.channel }}
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: packages/fwfh_text_style
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run git fetch
        run: |
          git config user.name name
          git config user.email email@domain.com
          git fetch
      - run: git merge -m test origin/release/${{ matrix.channel }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - run: flutter --version
      - run: flutter test
