name: Backward compatibility
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        package:
          - core
          - enhanced
          - fwfh_cached_network_image
          - fwfh_chewie
          - fwfh_just_audio
          - fwfh_svg
          - fwfh_url_launcher
          - fwfh_webview

    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    env:
      GOLDEN_SKIP: "yes"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Update pubspec.yaml
        run: |
          set -e

          sudo snap install yq

          # delete all overrides and use pub.dev versions
          yq e 'del(.dependency_overrides)' -i pubspec.yaml

          # back up SDK constraint
          _sdkVersion=$( yq e .environment.sdk pubspec.yaml )

          # replace:
          #   foo: ^1.0.0
          #   bar: ^2.0.0-0
          # into:
          #   foo: 1.0.0
          #   bar: ^2.0.0-0 (unchanged)
          sed -i'' -e 's#^\(  [^:]*\): ^\([0-9.]*\)$#\1: \2#' pubspec.yaml

          # replace:
          #   foo: ">=1.0.0" 
          #   bar: ">=2.0.0 <4.0.0"
          #   yolo: ">=3.0.0-0"
          # into:
          #   foo: 1.0.0
          #   bar: 2.0.0
          #   yolo: ">=3.0.0-0" (unchanged)
          sed -i'' -e 's#^\(  [^:]*\): ">=\([0-9.]*\)\( <.*\)\{0,1\}"$#\1: \2#' pubspec.yaml

          # restore SDK constraint
          yq e ".environment.sdk = \"${_sdkVersion}\"" -i pubspec.yaml

          # extract Flutter version to install later
          _flutterVersion=$( yq e '.environment.flutter' pubspec.yaml | sed -e 's/^>=//' | sed -e 's/-0$//' )
          echo "FLUTTER_VERSION=${_flutterVersion}" >> $GITHUB_ENV

          # output for debugging
          cat pubspec.yaml

      - name: Setup Flutter
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          cache: true
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter test

  core:
    strategy:
      matrix:
        channel:
          - beta
          - master
          - stable

    # In case one of these fails, create a new PR against the `release/*` branch
    # and publish a new version to make sure there is a compatible version
    # of `fwfh_text_style` for all active Flutter versions.
    name: core@${{ matrix.channel }}
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: packages/core
    env:
      GOLDEN_SKIP: "yes"
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Update pubspec.yaml
        run: |
          set -e

          sudo snap install yq

          # delete all overrides and use pub.dev versions
          yq e 'del(.dependency_overrides)' -i pubspec.yaml

          # output for debugging
          cat pubspec.yaml
      - name: Setup Flutter
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          cache: true
          channel: ${{ matrix.channel }}
      - run: flutter test
