name: fwfh_webview
version: 0.6.2+1
description: WidgetFactory extension to render IFRAME with the official WebView plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=2.5.0"
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.6.1 <0.9.0"
  webview_flutter: ">=2.2.0 <4.0.0"

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core
  fwfh_text_style:
    path: ../fwfh_text_style

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  measurer: ^2.1.1
