name: fwfh_webview
version: 0.15.1-rc.1
description: WidgetFactory extension to render IFRAME with the official WebView plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html

environment:
  flutter: ">=3.16.0"
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: "<0.15.2"
  logging: ^1.0.0
  web: ">=0.3.0 <0.6.0"
  webview_flutter: ^4.0.1
  webview_flutter_android: ^3.10.0
  webview_flutter_wkwebview: ^3.6.0

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: any
  measurer: ^2.1.1
  plugin_platform_interface: any
  webview_flutter_platform_interface: ^2.4.0

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - iframe
  - fwfh
